### ISSUE TITLE
闰月

### ISSUE THREAD

**Issue by 476229182** [opprime/calendarist#2]
阳历的2014年10月24号，农历为闰九月初一
每年生成生日时，能否是闰月时生成闰月对应的阳历，非闰月时生成非闰月对应的阳历
2015年时Calendarist calendarist = Calendarist.fromLunar(2015, 9, 1);
calendarist.set(Calendarist.LEAP_MONTH_OF_CURRENT, 1);
阳历为2015.2.19

**Comment by opprime** [comment]
> 阳历的2014年10月24号，农历为闰九月初一
> 每年生成生日时，能否是闰月时生成闰月对应的阳历，非闰月时生成非闰月对应的阳历
> 2015年时Calendarist calendarist = Calendarist.fromLunar(2015, 9, 1);
> calendarist.set(Calendarist.LEAP_MONTH_OF_CURRENT, 1);
> 阳历为2015.2.19

你的意思是：
因为2015年是没有闰月的，但是假如给农历2015年的某天设置了LEAP_MONTH_OF_CURRENT为1，即设置了有闰月，就生成了错误的阳历日期，是吧。

**Comment by 476229182** [comment]
Calendar cal = Calendar.getInstance();
cal.setTime(toDate(sDate));
Calendarist calendarist = Calendarist.fromLunar(cal.get(Calendar.YEAR), cal.get(Calendar.MONTH) + 1, cal.get(Calendar.DAY_OF_MONTH));
int leapMonths = CalendaristUtils.leapMonth(cal.get(Calendar.YEAR));
if (leapMonths > 0 && leapMonths == cal.get(Calendar.MONTH) + 1) {
    calendarist.set(Calendarist.LEAP_MONTH_OF_CURRENT, leapMonth);
}
改成这样了，不知道是否正确？

**Comment by opprime** [comment]
思路是一样的，已提交更新到1.0.6

**Comment by opprime** [comment]
> Calendar cal = Calendar.getInstance();
> cal.setTime(toDate(sDate));
> Calendarist calendarist = Calendarist.fromLunar(cal.get(Calendar.YEAR), cal.get(Calendar.MONTH) + 1, cal.get(Calendar.DAY_OF_MONTH));
> int leapMonths = CalendaristUtils.leapMonth(cal.get(Calendar.YEAR));
> if (leapMonths > 0 && leapMonths == cal.get(Calendar.MONTH) + 1) {
> calendarist.set(Calendarist.LEAP_MONTH_OF_CURRENT, leapMonth);
> }
> 改成这样了，不知道是否正确？

思路是一样的，已提交更新到1.0.6

**Comment by 476229182** [comment]
好的，感谢！
