### ISSUE TITLE
发现了日期与万年历对应不上的问题

### ISSUE THREAD

**Issue by tabbbbb** [opprime/calendarist#4]
首先非常感谢您这边的工具，解决了我们开发过程中很大的难题，我们在使用的过程中发现，根据工具算出来的时间与万年历对应不上，例如1990年5月12日，工具算出来是乙亥日，实际上应该是丁丑日 还有1990年6月11日  工具：丙午日，实际：丁未日，好像都少了一天

**Comment by opprime** [comment]
> 首先非常感谢您这边的工具，解决了我们开发过程中很大的难题，我们在使用的过程中发现，根据工具算出来的时间与万年历对应不上，例如1990年5月12日，工具算出来是乙亥日，实际上应该是丁丑日 还有1990年6月11日 工具：丙午日，实际：丁未日，好像都少了一天

感谢反馈，我试了下，某些年月确实有这个问题，近期会尽快解决！

**Comment by tabbbbb** [comment]
非常感谢

**Comment by opprime** [comment]
问题已修复，已提交v1.0.7版本！
